version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
      - ./history_log.json:/app/history_log.json
    ports:
      - "8507:8507"
    command: ["uvicorn", "src.api:app", "--host", "0.0.0.0", "--port", "8507"]